<?php
try {
    $name = $_POST['name'];
    $phoneNumber = $_POST['phoneNumber'];
    $topic = $_POST['messageTopic'];
    $comment = $_POST['comment'];
    $acces = $_POST['acces'];
} catch (\Throwable $th) {
    $name = 'error';
    $phoneNumber = 'error';
    $topic = 'error';
    $comment = 'error';
    $acces = 'error';
}

$token = "8692677184:AAFH9TjUKPzdgAozkhkNKpGy_zB1QmrXBzo"; // Token, generated by Bot Father
$chat_id = 5340650124; // Number of active chat from https://api.telegram.org/bot<Token>/getUpdates

$name = urlencode($name);
$phoneNumber = urlencode($phoneNumber);
$topic = urlencode($topic);
$comment = urlencode($comment);
$news = urlencode($news);

$urlQuery = "https://api.telegram.org/bot$token/sendMessage?chat_id=$chat_id&text=" .
    "***<b>Заявка</b>***\n" . "\n\n" .
    "<u>Ім'я замовника</u>: <b>$name</b>\n" .
    "<u>Номер замовнка</u>: <b>$phoneNumber</b>\n" .
    "<u>Тема повідомлення</u>: <b>$topic</b>\n" .
    "<u>Підтвердження</u>: <b>$acces</b>\n" . "\n\n";
if($comment !="") {
    $urlQuery .= "<u>Кометар</u>: <i>$comment</i>\n";
}

$urlQuery .= "&parse_mode=HTML";

$result = file_get_contents($urlQuery);
?>