

<?php
try {
    $name = $_POST['name'];
    $phoneNumber = $_POST['phoneNumber'];
    $topic = $_POST['messageTopic'];
    $comment = $_POST['comment'];
    $acces = $_POST['acces'];
} catch (\Throwable $th) {
    $name = 'error';
    $phoneNumber = 'error';
    $topic = 'error';
    $comment = 'error';
    $acces = 'error';
}

$token = "8692677184:AAFH9TjUKPzdgAozkhkNKpGy_zB1QmrXBzo"; // Token, generated by Bot Father
$chat_id = 5340650124; // Number of active chat from https://api.telegram.org/bot<Token>/getUpdates

// $name = urlencode($name);
// $phoneNumber = urlencode($phoneNumber);
// $topic = urlencode($topic);
// $comment = urlencode($comment);
// $news = urlencode($news);

$urlQuery = "https://api.telegram.org/bot$token/sendMessage?chat_id=$chat_id&text=" .
    "***<b>Заявка</b>***%0A" . "%0A%0A" .
    "<u>Ім'я замовника</u>: <b>$name</b>%0A" .
    "<u>Номер замовнка</u>: <b>$phoneNumber</b>%0A" .
    "<u>Тема повідомлення</u>: <b>$topic</b>%0A" .
    "<u>Підтвердження</u>: <b>$acces</b>%0A" . "%0A%0A";
if($comment !="") {
    $urlQuery .= "<u>Кометар</u>: <i>$comment</i>%0A";
}

$urlQuery .= "&parse_mode=HTML";

$result = file_get_contents($urlQuery);
?>

<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <title>send_form</title>
    <link rel="stylesheet" href="css/style.css">
    <meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=0.1, maximum-scale=2.0, minimum-scale=1.0">
</head>
<body>
    <div class="black_background" id="black"></div>
    <div class="popup" id="popup">
        <form action="popup.php" method="post">
            <h2>Замовити дзвінок</h2>
            <label><input type="text" name="name" placeholder="Ваше ім'я"></label>
            <label><input type="tel" name="phone" placeholder="Телефон"></label>
            <button type="submit">Відправити</button>
        </form>
        <a class="cancel_popup" id="cancel_popup">x</a>
    </div>
    <header>
        <div class="wrapper">
            <div class="flex_between">
                <nav class="nav_header align_items">
                    <ul class="list_header" id="menu">
                        <li class="cancel" id="cancel"><a href="#">x</a></li>
                        <li><a class="grey" href="#">Головна</a></li>
                        <li><a class="grey" href="#">Про компанію</a></li>
                        <li class="our_houses">
                            <a id="btn" class="grey" href="houses.html">Наші будівлі</a>
                            <ul id="submenu" class="submenu">
                                <li><a class="arrow br1" href="#">Таунхауси</a></li>
                                <li><a class="arrow" href="#">Пентхауси</a></li>
                                <li><a class="arrow" href="#">Котеджі</a></li>
                                <li class="dog">
                                    <a id="subbtn" class="arrow br2" href="#">Собачі будки</a>
                                    <ul id="subsubmenu" class="subsubmenu">
                                        <li><a class="br1" href="#">Елітні будки</a></li>
                                        <li><a href="#">Для чіхуахуа</a></li>
                                        <li><a href="#">Вольєри</a></li>
                                        <li class="last br2"><a href="#">Халабуди</a></li>
                                        <li class="cancelsubsub2"><a id="cancelsubsub" class="cancelsubsub" href="#">x</a></li>
                                    </ul>
                                </li>
                                <li class="cancelsub2"><a id="cnacelsub" class="cancelsub" href="#">x</a></li>
                            </ul>
                        </li>
                        <li><a class="grey" href="#">Акції</a></li>
                        <li><a class="grey" href="contacts.html">Контакти</a></li>
                    </ul>
                </nav>
                <nav class="social_nav">
                    <ul class="list_social flex_between align_items">
                        <li>
                            <a href="#" class="fb">
                                <svg version="1.2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 19" width="10" height="19">
                                    <path class="a" d="m2.7 18.2h3.3v-8h2.6l0.4-3.2h-3v-2.2q0-0.8 0.3-1.1 0.3-0.5 1.3-0.5h1.7v-2.8q-1-0.2-2.5-0.2-1.8 0-3 1.2-1.1 1.1-1.1 3.1v2.5h-2.7v3.2h2.7z" />
                                </svg>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="tw">
                                <svg version="1.2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 15" width="18" height="15">
                                    <path class="a" d="m16.1 3.6q1.1-0.8 1.9-1.9-1.1 0.4-2.1 0.6 1.2-0.8 1.6-2.1-1.1 0.7-2.3 0.9-0.6-0.5-1.3-0.8-0.6-0.4-1.5-0.4-0.9 0-1.8 0.5-0.8 0.5-1.3 1.4-0.5 0.8-0.5 1.8 0 0.5 0.1 0.9-2.3-0.1-4.3-1.2-2-1-3.3-2.7-0.6 0.9-0.6 1.9 0 0.9 0.5 1.7 0.5 0.8 1.2 1.4-0.9-0.1-1.7-0.5 0 1.3 0.9 2.4 0.8 1 2.1 1.3-0.5 0.1-1 0.1-0.3 0-0.7-0.1 0.4 1.1 1.3 1.8 1 0.8 2.2 0.8-2.1 1.5-4.6 1.5-0.5 0-0.9 0 2.6 1.7 5.7 1.7 3.2 0 5.7-1.7 2.3-1.5 3.5-4 1.3-2.3 1.3-4.8 0-0.4-0.1-0.5z" />
                                </svg>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="inst">
                                <svg version="1.2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 19 19" width="19" height="19">
                                    <path class="a" d="m9.2 4.4q1.3 0 2.3 0.6 1.1 0.7 1.8 1.8 0.6 1.1 0.6 2.3 0 1.3-0.6 2.4-0.7 1.1-1.8 1.7-1 0.6-2.3 0.6-1.3 0-2.4-0.6-1.1-0.6-1.7-1.7-0.6-1.1-0.6-2.4 0-1.2 0.6-2.3 0.6-1.1 1.7-1.8 1.1-0.6 2.4-0.6zm0 7.8q1.3 0 2.2-0.9 0.9-0.9 0.9-2.2 0-1.2-0.9-2.1-0.9-1-2.2-1-1.3 0-2.2 1-0.9 0.9-0.9 2.1 0 1.3 0.9 2.2 0.9 0.9 2.2 0.9zm6-8q0-0.4-0.3-0.8-0.3-0.3-0.8-0.3-0.4 0-0.8 0.3-0.3 0.4-0.3 0.8 0 0.5 0.3 0.8 0.4 0.3 0.8 0.3 0.5 0 0.8-0.3 0.3-0.3 0.3-0.8zm3.1 1.1q0.1 1.2 0.1 3.8 0 2.7-0.1 3.9 0 1.1-0.3 2-0.4 1-1.2 1.8-0.7 0.7-1.7 1.1-0.9 0.3-2.1 0.4-1.1 0-3.8 0-2.7 0-3.8 0-1.2-0.1-2.1-0.4-1-0.4-1.8-1.1-0.7-0.8-1.1-1.8-0.3-0.9-0.3-2-0.1-1.2-0.1-3.9 0-2.6 0.1-3.8 0-1.2 0.3-2 0.4-1.1 1.1-1.8 0.8-0.8 1.8-1.2 0.9-0.2 2.1-0.3 1.1-0.1 3.8-0.1 2.7 0 3.8 0.1 1.2 0.1 2.1 0.3 1 0.4 1.7 1.2 0.8 0.7 1.2 1.8 0.3 0.8 0.3 2zm-1.9 9.2q0.2-0.7 0.3-2.2 0-0.9 0-2.5v-1.3q0-1.7 0-2.6-0.1-1.5-0.3-2.2-0.5-1.3-1.8-1.8-0.7-0.2-2.2-0.3-0.9 0-2.6 0h-1.3q-1.6 0-2.5 0-1.5 0.1-2.2 0.3-1.3 0.5-1.8 1.8-0.2 0.7-0.3 2.2-0.1 0.9-0.1 2.6v1.3q0 1.6 0.1 2.5 0.1 1.5 0.3 2.2 0.5 1.3 1.8 1.8 0.7 0.2 2.2 0.3 0.9 0.1 2.5 0.1h1.3q1.7 0 2.6-0.1 1.5-0.1 2.2-0.3 1.3-0.5 1.8-1.8z" />
                                </svg>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="burger" id="burger">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </header>
    <div class="header_2">
        <div class="wrapper flex_between align_items">
            <div class="logo">
                <a href="index.html">
                    <picture class="logo">
                        <source srcset="img/logo.webp" type="image/webp">
                        <img src="img/logo.png" alt="logo">
                    </picture>
                </a>
            </div>
            <div class="tel th border">
                <p>
                    <a class="black" href="tel:+380971002525">
                        <img src="img/phone.svg" alt="phone icon">
                        +38(097) 100-25-25
                    </a>
                </p>
                <p class="phone"><a class="black" href="tel:+380971002525">+38(097) 100-25-25</a></p>
            </div>
            <div class="social_media sh">
                <div class="email">
                    <a class="black" href="mailto:hataplus@hata.com.ua@gmail.com">
                        <img src="img/mail.svg" alt="email icon">
                        hataplus@hata.com.ua
                    </a>
                </div>
                <div class="skype">
                    <a class="black" href="#">
                        <img src="img/skype.svg" alt="skype icon">
                        hataplus
                    </a>
                </div>
            </div>
            <p class="cta_container black">
                <a href="#" class="cta black" id="open_popup">Замовити дзвінок</a>
            </p>
        </div>
    </div>
    <main class="send wrapper">
        <div class="info">
            <h1>Реєстрація завершена</h1>
            <div>
                <p>Ім'я користувача: <?= $name ?></p>
                <p>Номер телефону: <?= $phoneNumber ?></p>
                <p>Тема повідомлення: <?= $topic ?></p>
            </div>
        </div>
        <a href="index.html" class="form_return">Повернутися на головну</a>
    </main>
    <footer>
        <div class="wrapper flex_between footer_inside">
            <nav class="list1">
                <ul class="list_footer">
                    <li><a class="six houses" href="#">Будинки</a></li>
                    <li><a class="six" href="#">Iнфраструктура</a></li>
                    <li><a class="six" href="#">Сервіс</a></li>
                    <li><a class="six" href="#">Новини</a></li>
                </ul>
            </nav>
            <nav class="list2">
                <ul class="list_footer">
                    <li><a class="six" href="#">Про компанію</a></li>
                    <li><a class="six" href="#">Страхування</a></li>
                    <li><a class="six" href="#">Контакти</a></li>
                </ul>
            </nav>
            <div class="tel tf">
                <p>
                    <a class="black" href="tel:+380971002525">
                        <img src="img/phone.svg" alt="phone icon">
                        +38(097) 100-25-25
                    </a>
                </p>
                <p class="phone"><a class="black" href="tel:+380971002525">+38(097) 100-25-25</a></p>
            </div>
            <div class="social_media sf">
                <div class="email">
                    <a class="black" href="mailto:hataplus@hata.com.ua@gmail.com">
                        <img src="img/mail.svg" alt="email icon">
                        hataplus@hata.com.ua
                    </a>
                </div>
                <div class="skype">
                    <a class="nostyle black" href="#">
                        <img src="img/skype.svg" alt="skype icon">
                        hataplus
                    </a>
                </div>
            </div>
        </div>
    </footer>
    <div class="construction">
        <p>© Будівельна компанія “Хата Плюс” 2018.</p>
    </div>
    <script src="java/script.js"></script>
</body>
</html>